## ddd_simulation.R
## ----------------------------------------------------------------------
## Triple-diff simulation: shows DiD biased by differential state-level
## trends, placebo DiD also biased the SAME WAY, and DDD recovers ATT.
##
## DGP (port of CI-2/Lab/DDD/ddd2.R by Cunningham & Butts, 2024):
##   - 40 states × 50 cities × 3 worker groups × 11 years (2010–2020)
##   - States 1–20 are "experimental" (mandate states), 21–40 are control
##   - Worker 1 = single men;  Worker 2 = married women 20-40;  Worker 3 = older women
##   - Treatment: starting 2015, mandate states' married women 20-40 take a
##     wage hit of $5,000 (the ATT we want to recover)
##   - Differential trend: mandate states have a different state trend
##     than control states -- this is what breaks the naive 2x2 DiD
##
## Output:
##   - console: DiD-biased ≈ -$7,487
##              Placebo DiD ≈ -$2,507  (the bias itself)
##              DDD ≈ -$4,972  (close to the true ATT of -$5,000)
##   - figures/triple_diff_trends.pdf
##   - figures/triple_diff_eventstudy.pdf
##   - tables/triple_diff_cells.tex (8-cell table for the deck)
## ----------------------------------------------------------------------

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(fixest)
  library(broom)
})

source(file.path("..", "..", "..", "..", "_themes", "remix_theme.R"))

set.seed(20200403)

## ---- DGP ----------------------------------------------------------------
df <- expand_grid(
  state  = 1:40,
  city   = 1:50,
  worker = 1:3,                    # 1 = men, 2 = married women, 3 = older women
  year   = 2010:2020
)

df$experimental <- as.numeric(df$state <= 20)
df$after        <- as.numeric(df$year >= 2015)

df$city <- fixest::to_integer(df$state, df$city)
df$id   <- fixest::to_integer(df$state, df$city, df$worker)

# Baseline earnings differ across worker groups
df$baseline <- case_when(
  df$worker == 1 ~ 50000,
  df$worker == 2 ~ 45000,
  df$worker == 3 ~ 40000
)
# Mandate states start 50% higher (just a level shift -- irrelevant for DiD)
df$baseline <- if_else(df$experimental == 1, df$baseline * 1.5, df$baseline)

df$year_diff <- df$year - 2010

# *** THE NON-PARALLEL TREND ***
# Mandate states trend at $1,000/yr, control states at $1,500/yr.
# Married women have an extra $500/yr group trend (vs $1,000 for men/older women).
# Together these create a state-level differential trend that biases the simple DiD.
df$state_trend <- if_else(df$experimental == 1, 1000, 1500)
df$group_trend <- if_else(df$worker == 2,       500, 1000)

df$error <- rnorm(nrow(df), mean = 0, sd = 1500)
df$y0    <- df$baseline + df$state_trend * df$year_diff +
                          df$group_trend * df$year_diff + df$error

# Treatment: -$5,000 ATT for married women in mandate states post-2015
df$treat    <- (df$experimental == 1 & df$worker == 2 & df$after == 1)
df$y1       <- df$y0 - 5000 * df$treat
df$earnings <- df$treat * df$y1 + (1 - df$treat) * df$y0

## ---- 8 cells ------------------------------------------------------------
cell <- function(after_v, exp_v, married_v) {
  with(df, mean(earnings[after == after_v & experimental == exp_v &
                         (worker == 2) == married_v]))
}

# married women cells
ame <- cell(1, 1, TRUE);  bme <- cell(0, 1, TRUE)
amn <- cell(1, 0, TRUE);  bmn <- cell(0, 0, TRUE)
# placebo (single men + older women) cells
asoe <- cell(1, 1, FALSE); bsoe <- cell(0, 1, FALSE)
ason <- cell(1, 0, FALSE); bson <- cell(0, 0, FALSE)

## ---- Three estimators ---------------------------------------------------
DiD_naive   <- (ame  - bme)  - (amn  - bmn)
DiD_placebo <- (asoe - bsoe) - (ason - bson)
DDD         <- DiD_naive - DiD_placebo

cat("------- THREE ESTIMATORS -------\n")
cat(sprintf("True ATT (built into DGP):  -5,000\n"))
cat(sprintf("Naive DiD  (married only):  %+.0f  <-- biased\n", DiD_naive))
cat(sprintf("Placebo DiD (men + older):  %+.0f  <-- the bias itself\n", DiD_placebo))
cat(sprintf("Triple Diff (DiD - Plac):   %+.0f  <-- recovers the ATT\n", DDD))

## ---- 8-cell LaTeX table for the deck -----------------------------------
tbl_lines <- c(
  "% Auto-generated by ddd_simulation.R -- do not hand-edit",
  "\\begin{tabular}{@{}lcccc@{}}",
  "\\toprule",
  " & \\multicolumn{2}{c}{\\textbf{Mandate states}} & \\multicolumn{2}{c}{\\textbf{Control states}} \\\\",
  "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
  " & Pre & Post & Pre & Post \\\\",
  "\\midrule",
  sprintf("Married women 20--40        & %s & %s & %s & %s \\\\",
          format(round(bme),  big.mark=","), format(round(ame),  big.mark=","),
          format(round(bmn),  big.mark=","), format(round(amn),  big.mark=",")),
  sprintf("Placebo (men + older women) & %s & %s & %s & %s \\\\",
          format(round(bsoe), big.mark=","), format(round(asoe), big.mark=","),
          format(round(bson), big.mark=","), format(round(ason), big.mark=",")),
  "\\bottomrule",
  "\\end{tabular}"
)
dir.create("../../tables", showWarnings = FALSE, recursive = TRUE)
writeLines(tbl_lines, "../../tables/triple_diff_cells.tex")
cat("\nWrote: ../../tables/triple_diff_cells.tex\n")

## ---- Trends figure ------------------------------------------------------
# Average earnings by state-type × group × year for the plot
trends <- df %>%
  mutate(
    group   = case_when(worker == 2 ~ "Married women 20-40",
                        TRUE        ~ "Placebo: men + older women"),
    state_type = if_else(experimental == 1, "Mandate states",  "Control states")
  ) %>%
  group_by(year, group, state_type) %>%
  summarise(earnings = mean(earnings), .groups = "drop")

p_trends <- ggplot(trends, aes(x = year, y = earnings,
                               color = state_type, linetype = group)) +
  geom_vline(xintercept = 2014.5,
             color = remix_color("warmgray"), linewidth = 0.5,
             linetype = "dotted") +
  annotate("text", x = 2014.6, y = 95000,
           label = "mandate begins",
           color = remix_color("warmgray"),
           size = 3.0, fontface = "italic", hjust = 0) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 1.6) +
  scale_color_manual(values = c("Mandate states" = remix_color("forest"),
                                "Control states" = remix_color("ocean")),
                     name = NULL) +
  scale_linetype_manual(values = c("Married women 20-40" = "solid",
                                   "Placebo: men + older women" = "longdash"),
                        name = NULL) +
  scale_x_continuous(breaks = seq(2010, 2020, 2)) +
  scale_y_continuous(labels = function(x) paste0("$", format(x/1000, big.mark=","), "k")) +
  labs(
    title    = "Two diff-in-diffs. One bias. Both groups feel the same differential trend.",
    subtitle = "Treated cells (married women × mandate states) drop $5,000 in 2015. The placebo group does NOT -- but its DiD is still biased.",
    x = NULL, y = "Mean earnings",
    caption = "Simulated DGP. Mandate states trend $500/yr SLOWER than control states. That trend bias hits BOTH groups equally -- the basis for DDD."
  ) +
  theme_remix() +
  theme(legend.position = "bottom",
        legend.box = "vertical",
        legend.spacing.y = unit(-3, "pt"))

remix_save("../../figures/triple_diff_trends.pdf", p_trends,
           width = 9.4, height = 5.2)
cat("Saved: ../../figures/triple_diff_trends.pdf\n")

## ---- Event-study coefplot ----------------------------------------------
df$treated1 <- case_when(
  df$experimental == 1 & df$worker == 2 ~ 1,
  df$worker == 2 ~ 0,
  .default = NA_integer_
)
df$treated_placebo <- case_when(
  df$experimental == 1 & df$worker %in% c(1, 3) ~ 1,
  df$worker %in% c(1, 3) ~ 0,
  .default = NA_integer_
)
df$married_women <- as.numeric(df$worker == 2)

df$treated1_x_year <- if_else(df$treated1 == 1, df$year * df$treated1, 2014)
es_treated1 <- feols(
  earnings ~ i(treated1_x_year, ref = 2014) | year + treated1,
  df, cluster = ~state
)

df$placebo_x_year <- if_else(df$treated_placebo == 1, df$year * df$treated_placebo, 2014)
es_placebo <- feols(
  earnings ~ i(placebo_x_year, ref = 2014) | year + treated_placebo,
  df, cluster = ~state
)

es_triple <- feols(
  earnings ~ i(year, experimental * married_women) +
    i(year) + i(experimental) + i(married_women) +
    i(year, experimental) + i(year, married_women) +
    i(experimental * married_women),
  data = df, cluster = ~state
)

pts_treated1 <- es_treated1 |> broom::tidy() |>
  mutate(estimator = "Naive DiD (biased)",
         year = as.numeric(sub("treated1_x_year::", "", term)))
pts_placebo  <- es_placebo  |> broom::tidy() |>
  mutate(estimator = "Placebo DiD (also biased)",
         year = as.numeric(sub("placebo_x_year::", "", term)))
pts_triple   <- es_triple   |> broom::tidy() |>
  filter(grepl("year::.*:experimental \\* married_women", term)) |>
  mutate(estimator = "Triple Diff (unbiased)",
         year = as.numeric(sub("year::(.*):experimental.*", "\\1", term)))

pts <- bind_rows(pts_treated1, pts_placebo, pts_triple) |>
  filter(!is.na(year))
pts$estimator <- factor(pts$estimator,
                        levels = c("Naive DiD (biased)",
                                   "Placebo DiD (also biased)",
                                   "Triple Diff (unbiased)"))

p_es <- ggplot(pts, aes(x = year, y = estimate, color = estimator)) +
  geom_hline(yintercept = 0, color = remix_color("charcoal"),
             linewidth = 0.4, linetype = "dashed") +
  geom_hline(yintercept = -5000, color = remix_color("warmgray"),
             linewidth = 0.4, linetype = "dotted") +
  annotate("text", x = 2010.1, y = -5000,
           label = "true ATT = -$5,000",
           color = remix_color("warmgray"),
           size = 2.7, fontface = "italic", hjust = 0, vjust = -0.5) +
  geom_vline(xintercept = 2014.5, color = remix_color("warmgray"),
             linewidth = 0.4, linetype = "dotted") +
  geom_errorbar(aes(ymin = estimate - 1.96*std.error,
                    ymax = estimate + 1.96*std.error),
                width = 0.18, linewidth = 0.5) +
  geom_point(size = 2.3) +
  scale_color_manual(values = c(
    "Naive DiD (biased)"        = remix_color("ocean"),
    "Placebo DiD (also biased)" = remix_color("warmgray"),
    "Triple Diff (unbiased)"    = remix_color("forest")
  ), name = NULL) +
  scale_x_continuous(breaks = 2010:2020) +
  scale_y_continuous(labels = function(x) paste0("$", format(x, big.mark=","))) +
  labs(
    title    = "Two biased DiDs, one unbiased Triple Diff",
    subtitle = "The bias of the naive DiD equals the placebo DiD. Subtract them -- get the ATT.",
    x = NULL, y = "Event-study coefficient",
    caption = "95% CI; SE clustered at state. The two biased DiDs track each other above zero; the DDD lands near -$5,000 after treatment."
  ) +
  theme_remix() +
  theme(legend.position = "bottom")

remix_save("../../figures/triple_diff_eventstudy.pdf", p_es,
           width = 9.4, height = 5.2)
cat("Saved: ../../figures/triple_diff_eventstudy.pdf\n")
